In [5]:
import pandas as pd
import numpy as np

from itertools import product

In [7]:
res = np.load("./res_list.npy")

att_name = np.array(["Bald",
"Bangs",
"Black_Hair",
"Blond_Hair",
"Brown_Hair",
"Bushy_Eyebrows",
"Eyeglasses",
"Male",
"Mouth_Slightly_Open",
"Mustache",
"No_Beard",
"Pale_Skin",
"Young"])
att_name_list = np.array([7,12,9,10,0])
print(att_name[att_name_list])

res = res.squeeze()
data = []
for i in range(att_name_list.shape[0]):
    if(att_name[att_name_list[i]] == "No_Beard"):
        data.append(-1*res[:,i])
    else:
        data.append(res[:,i])
data = np.array(data).astype(int)
data = np.maximum(data, 0)
print(data)

perm_array = np.array(list(product([0, 1], repeat=5)))
prob_array = []

for arr in perm_array:
    p = ((data.T == arr).sum(axis=1) == 5).mean()
    prob_array.append(p)

prob_array = np.array(prob_array)
prob_array

['Male' 'Young' 'Mustache' 'No_Beard' 'Bald']
[[0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 1 1 ... 1 0 1]
 [0 0 0 ... 0 0 0]]


array([0.093, 0.002, 0.378, 0.118, 0.   , 0.   , 0.208, 0.001, 0.025,
       0.   , 0.034, 0.045, 0.   , 0.   , 0.027, 0.   , 0.001, 0.   ,
       0.067, 0.   , 0.   , 0.   , 0.001, 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   ])

In [8]:


dataset = pd.read_csv("list_attr_celeba.txt", sep = ' ', header=1, skiprows = 0)

data = np.vstack((dataset['Male'], dataset["Young"], dataset["Mustache"], (-dataset["No_Beard"]),\
                                                                dataset["Bald"]))

# np.where(data > 0, data, 0)
data=np.maximum(data, 0)
print("0:Male, 1:Young, 2: Mustache, 3:Beard, 4:Bald")
print(data.sum(axis=1))
print(data)

0:Male, 1:Young, 2: Mustache, 3:Beard, 4:Bald
[ 84434 156734   8417  33441   4547]
[[0 0 1 ... 1 0 0]
 [1 1 1 ... 1 1 1]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [9]:
perm_array = np.array(list(product([0, 1], repeat=5)))

In [11]:
prob_array_ori = []

for arr in perm_array:
    p = ((data.T == arr).sum(axis=1) == 5).mean()
    prob_array_ori.append(p)

prob_array_ori = np.array(prob_array_ori)
prob_array_ori

array([7.32037177e-02, 1.97434341e-05, 2.02370199e-04, 0.00000000e+00,
       4.93585852e-06, 0.00000000e+00, 4.93585852e-06, 0.00000000e+00,
       5.09262139e-01, 6.41661607e-05, 4.78778276e-04, 0.00000000e+00,
       4.93585852e-06, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       8.62985503e-02, 1.04344049e-02, 3.10317425e-02, 4.33861964e-03,
       5.57752013e-04, 6.91020193e-05, 1.78332568e-02, 2.38401966e-03,
       1.52745078e-01, 1.75222977e-03, 8.60764367e-02, 2.54690300e-03,
       4.83714135e-04, 3.94868681e-05, 1.93683088e-02, 7.94673221e-04])

In [12]:
(((prob_array_ori-prob_array)**2).mean())**0.5

0.12232304681835182

In [47]:
perm_array

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 1, 1],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 0, 1],
       [0, 0, 1, 1, 0],
       [0, 0, 1, 1, 1],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 1],
       [0, 1, 0, 1, 0],
       [0, 1, 0, 1, 1],
       [0, 1, 1, 0, 0],
       [0, 1, 1, 0, 1],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 1],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 1, 0],
       [1, 0, 0, 1, 1],
       [1, 0, 1, 0, 0],
       [1, 0, 1, 0, 1],
       [1, 0, 1, 1, 0],
       [1, 0, 1, 1, 1],
       [1, 1, 0, 0, 0],
       [1, 1, 0, 0, 1],
       [1, 1, 0, 1, 0],
       [1, 1, 0, 1, 1],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 0, 1],
       [1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1]])