In [31]:
import pandas as pd
import numpy as np

from itertools import product

In [37]:
res = np.load("./res_list.npy")

TypeError: load() got an unexpected keyword argument 'type'

In [13]:
att_name = np.array(["Bald",
"Bangs",
"Black_Hair",
"Blond_Hair",
"Brown_Hair",
"Bushy_Eyebrows",
"Eyeglasses",
"Male",
"Mouth_Slightly_Open",
"Mustache",
"No_Beard",
"Pale_Skin",
"Young"])
att_name_list = np.array([7,12,9,10,0])
print(att_name[att_name_list])

['Male' 'Young' 'Mustache' 'No_Beard' 'Bald']


In [48]:
res = res.squeeze()
data = []
for i in range(att_name_list.shape[0]):
    if(att_name[att_name_list[i]] == "No_Beard"):
        data.append(-1*res[:,i])
    else:
        data.append(res[:,i])
data = np.array(data).astype(int)
data = np.maximum(data, 0)
print(data)


[[0 1 1 ... 1 0 0]
 [1 1 0 ... 0 1 1]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]]


In [35]:


dataset = pd.read_csv("list_attr_celeba.txt", sep = ' ', header=1, skiprows = 0)

data = np.vstack((dataset['Male'], dataset["Young"], dataset["Mustache"], (-dataset["No_Beard"]),\
                                                                dataset["Bald"]))

# np.where(data > 0, data, 0)
data=np.maximum(data, 0)
print("0:Male, 1:Young, 2: Mustache, 3:Beard, 4:Bald")
print(data.sum(axis=1))
print(data)

0:Male, 1:Young, 2: Mustache, 3:Beard, 4:Bald
[ 84434 156734   8417  33441   4547]
[[0 0 1 ... 1 0 0]
 [1 1 1 ... 1 1 1]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [49]:
perm_array = np.array(list(product([0, 1], repeat=5)))

In [50]:
def joint_prob(arr):
    return ((data.T == arr).sum(axis=1) == 5).mean()

In [51]:
prob_array = []

for arr in perm_array:
    p = joint_prob(arr)
    prob_array.append(p)

prob_array = np.array(prob_array)
prob_array

array([0.139, 0.001, 0.002, 0.   , 0.002, 0.   , 0.   , 0.   , 0.335,
       0.002, 0.008, 0.001, 0.   , 0.   , 0.   , 0.001, 0.136, 0.029,
       0.048, 0.012, 0.002, 0.   , 0.023, 0.007, 0.156, 0.007, 0.069,
       0.005, 0.   , 0.   , 0.011, 0.004])

In [5]:
prob_array.sum()

1.0

In [47]:
perm_array

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 1, 1],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 0, 1],
       [0, 0, 1, 1, 0],
       [0, 0, 1, 1, 1],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 1],
       [0, 1, 0, 1, 0],
       [0, 1, 0, 1, 1],
       [0, 1, 1, 0, 0],
       [0, 1, 1, 0, 1],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 1],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 1, 0],
       [1, 0, 0, 1, 1],
       [1, 0, 1, 0, 0],
       [1, 0, 1, 0, 1],
       [1, 0, 1, 1, 0],
       [1, 0, 1, 1, 1],
       [1, 1, 0, 0, 0],
       [1, 1, 0, 0, 1],
       [1, 1, 0, 1, 0],
       [1, 1, 0, 1, 1],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 0, 1],
       [1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1]])